powershell: fix JBoss classloading issue with newer spring
Remove the java2ClassLoadingCompliance setting from the classloader to
ensure libraries from the WAR take precedence over JBoss provided
libraries in order to resolve this issue

  [ContextLoader] Context initialization failed
    java.lang.NoSuchMethodError: org.springframework.web.context.ConfigurableWebApplicationContext.setId(Ljava/lang/String;)V
      at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:264)

The problem here is that we're trying to use a Spring API which isn't
available in JBoss's version of Spring.

Also, exclude stax-api from resteasy-jaxb-provider dependencies so as
to ensure that JBoss's version is used avoiding this:

  java.lang.LinkageError: loader constraint violation: when resolving field
      "DATETIME" the class loader (instance of org/jboss/classloader/spi/base/BaseClassLoader)
      of the referring class, javax/xml/datatype/DatatypeConstants, and the class loader
      (instance of <bootloader>) for the field's resolved type, javax/xml/namespace/QName,
      have different Class objects for that type

Reported-by: Michael Pasternak <mpastern@redhat.com>